# Generated by Django 4.1.7 on 2023-02-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer', models.CharField(max_length=100, verbose_name='Company')),
                ('Name', models.CharField(max_length=100, verbose_name='Name of Phone')),
                ('Price', models.IntegerField(verbose_name='Price')),
                ('Characteristics', models.TextField(verbose_name='Full characteristics of Phone')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
    ]
