# Generated by Django 4.1.7 on 2023-02-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='Image',
            field=models.ImageField(default=1, upload_to='images/%Y', verbose_name='Image of Phone'),
            preserve_default=False,
        ),
    ]
