# Generated by Django 4.1.7 on 2023-03-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_phones_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer', models.CharField(max_length=100, verbose_name='Company')),
                ('Name', models.CharField(max_length=100, verbose_name='Name of Computer')),
                ('Price', models.IntegerField(verbose_name='Price')),
                ('Characteristics', models.TextField(verbose_name='Full characteristics of Computer')),
                ('Image', models.ImageField(upload_to='images/%Y', verbose_name='Image of Computer')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manufacturer', models.CharField(max_length=100, verbose_name='Company')),
                ('Name', models.CharField(max_length=100, verbose_name='Name of PhonHeadphone')),
                ('Price', models.IntegerField(verbose_name='Price')),
                ('Characteristics', models.TextField(verbose_name='Full characteristics of Headphones')),
                ('Image', models.ImageField(upload_to='images/%Y', verbose_name='Image of Headphones')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categories', models.CharField(max_length=100, verbose_name='Category of Product')),
                ('ID_Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.phones')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
    ]
