# Generated by Django 4.1.7 on 2023-03-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_computers_options_alter_headphones_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ID_Products',
            field=models.IntegerField(verbose_name='ID of Product'),
        ),
    ]
