# Generated by Django 4.1.7 on 2023-03-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_products_id_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category of Product')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.DeleteModel(
            name='Computers',
        ),
        migrations.DeleteModel(
            name='Headphones',
        ),
        migrations.DeleteModel(
            name='Phones',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Categories',
        ),
        migrations.RemoveField(
            model_name='products',
            name='ID_Products',
        ),
        migrations.AddField(
            model_name='products',
            name='characteristics',
            field=models.TextField(default=1, verbose_name='Full characteristics of Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=1, upload_to='images/%Y', verbose_name='Image of Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='manufacturer',
            field=models.CharField(default=1, max_length=100, verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Name of Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.categories'),
            preserve_default=False,
        ),
    ]
