# Generated by Django 4.1.7 on 2023-04-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_categories_delete_computers_delete_headphones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.URLField(default=1, verbose_name='URL for this product'),
            preserve_default=False,
        ),
    ]
